// @ts-check

import type from '../type.js';
import rarity from '../../attributes/rarity.js';

const defaults = {
    rarity: rarity.exotic,
    type  : type.trinket,
};

const config = [
    { name: 'A mummified goblin hand' },
    { name: 'A piece of crystal that faintly glows in the moonlight' },
    { name: 'A gold coin minted in an unknown land' },
    { name: 'A diary written in a language you don’t know' },
    { name: 'A brass ring that never tarnishes' },
    { name: 'An old chess piece made from glass' },
    { name: 'A pair of knucklebone dice, each with a skull symbol on the side that would normally show six pips' },
    { name: 'A small idol depicting a nightmarish creature that gives you unsettling dreams when you sleep near it' },
    { name: 'A rope necklace from which dangles four mummified elf fingers' },
    { name: 'The deed for a parcel of land in a realm unknown to you' },
    { name: 'A 1-ounce block made from an unknown material' },
    { name: 'A small cloth doll skewered with needles' },
    { name: 'A tooth from an unknown beast' },
    { name: 'An enormous scale, perhaps from a dragon' },
    { name: 'A bright green feather' },
    { name: 'An old divination card bearing your likeness' },
    { name: 'A glass orb filled with moving smoke' },
    { name: 'A 1-pound egg with a bright red shell' },
    { name: 'A pipe that blows bubbles' },
    { name: 'A glass jar containing a weird bit of flesh floating in pickling fluid' },
    { name: 'A tiny gnome-crafted music box that plays a song you dimly remember from your childhood' },
    { name: 'A small wooden statuette of a smug halfling' },
    { name: 'A brass orb etched with strange runes' },
    { name: 'A multicolored stone disk' },
    { name: 'A tiny silver icon of a raven' },
    { name: 'A bag containing forty-seven humanoid teeth, one of which is rotten' },
    { name: 'A shard of obsidian that always feels warm to the touch' },
    { name: 'A dragon’s bony talon hanging from a plain leather necklace' },
    { name: 'A pair of old socks' },
    { name: 'A blank book whose pages refuse to hold ink, chalk, graphite, or any other substance or marking' },
    { name: 'A silver badge in the shape of a five-pointed star' },
    { name: 'A knife that belonged to a relative' },
    { name: 'A glass vial filled with nail clippings' },
    { name: 'A rectangular metal device with two tiny metal cups on one end that throws sparks when wet' },
    { name: 'A white, sequined glove sized for a human' },
    { name: 'A vest with one hundred tiny pockets' },
    { name: 'A small, weightless stone block' },
    { name: 'A tiny sketch portrait of a goblin' },
    { name: 'An empty glass vial that smells of perfume when opened' },
    { name: 'A gemstone that looks like a lump of coal when examined by anyone but you' },
    { name: 'A scrap of cloth from an old banner' },
    { name: 'A rank insignia from a lost legionnaire' },
    { name: 'A tiny silver bell without a clapper' },
    { name: 'A mechanical canary inside a gnome-crafted lamp' },
    { name: 'A tiny chest carved to look like it has numerous feet on the bottom' },
    { name: 'A dead sprite inside a clear glass bottle' },
    { name: 'A metal can that has no opening but sounds as if it is filled with liquid' },
    { name: 'A glass orb filled with water, in which swims a clockwork goldfish' },
    { name: 'A silver spoon with an M engraved on the handle' },
    { name: 'A whistle made from gold-colored wood' },
    { name: 'A dead scarab beetle the size of your hand' },
    { name: 'Two toy soldiers, one with a missing head' },
    { name: 'A small box filled with different-sized buttons' },
    { name: 'A candle that can’t be lit' },
    { name: 'A tiny cage with no door' },
    { name: 'An old key' },
    { name: 'An indecipherable treasure map' },
    { name: 'A hilt from a broken sword' },
    { name: 'A rabbit’s foot' },
    { name: 'A glass eye' },
    { name: 'A cameo carved in the likeness of a hideous person' },
    { name: 'A silver skull the size of a coin' },
    { name: 'An alabaster mask' },
    { name: 'A pyramid of sticky black incense that smells very bad' },
    { name: 'A nightcap that, when worn, gives you pleasant dreams' },
    { name: 'A single caltrop made from bone' },
    { name: 'A gold monocle frame without the lens' },
    { name: 'A 1-inch cube, each side painted a different color' },
    { name: 'A crystal knob from a door' },
    { name: 'A small packet filled with pink dust' },
    { name: 'A fragment of a beautiful song, written as musical notes on two pieces of parchment' },
    { name: 'A silver teardrop earring made from a real teardrop' },
    { name: 'The shell of an egg painted with scenes of human misery in disturbing detail' },
    { name: 'A fan that, when unfolded, shows a sleeping cat' },
    { name: 'A set of bone pipes' },
    { name: 'A four-leaf clover pressed inside a book discussing manners and etiquette' },
    { name: 'A sheet of parchment upon which is drawn a complex mechanical contraption' },
    { name: 'An ornate scabbard that fits no blade you have found so far' },
    { name: 'An invitation to a party where a murder happened' },
    { name: 'A bronze pentacle with an etching of a rat’s head in its center' },
    { name: 'A purple handkerchief embroidered with the name of a powerful archmage' },
    { name: 'Half of a floorplan for a temple, castle, or some other structure' },
    { name: 'A bit of folded cloth that, when unfolded, turns into a stylish cap' },
    { name: 'A receipt of deposit at a bank in a far-flung city' },
    { name: 'A diary with seven missing pages' },
    { name: 'An empty silver snuffbox bearing an inscription on the surface that says “dreams”' },
    { name: 'An iron holy symbol devoted to an unknown god' },
    { name: 'A book that tells the story of a legendary hero’s rise and fall, with the last chapter missing' },
    { name: 'A vial of dragon blood' },
    { name: 'An ancient arrow of elven design' },
    { name: 'A needle that never bends' },
    { name: 'An ornate brooch of dwarven design' },
    { name: 'An empty wine bottle bearing a pretty label' },
    { name: 'A mosaic tile with a multicolored, glazed surface' },
    { name: 'A petrified mouse' },
    { name: 'A black pirate flag adorned with a dragon’s skull and crossbones' },
    { name: 'A tiny mechanical crab or spider that moves about when it’s not being observed' },
    { name: 'A glass jar containing lard with a label that reads, “Griffon Grease”' },
    { name: 'A wooden box with a ceramic bottom that holds a living worm with a head on each end of its body' },
    { name: 'A metal urn containing the ashes of a hero' },
];

export default config.map((item) => ({ ...defaults, ...item }));
